`timescale 1ns / 1ps
//-----------------------------------------------------------------------------
// synapse_csr.sv — Compressed-Sparse-Row Synapse Connectivity Store
//
// Description:
//   Stores the network connectivity the way a real event-driven neuromorphic
//   accelerator does: every synapse is grouped by its SOURCE neuron, so the
//   fan-out of a spiking neuron can be walked in O(fan-out) time instead of
//   scanning an N x N matrix.
//
//   Layout (all loaded from hex .mem files generated by python/train_snn.py):
//     csr_dst[j], csr_weight[j] : the j-th synapse (target id, signed weight)
//     src_start[s]              : index in csr_* where source s's list begins
//     src_count[s]              : number of synapses fanning out of source s
//
//   Interfaces:
//     - pointer lookup (combinational): src id -> (base index, length)
//     - synapse read (1-cycle latency) : flat index -> (dst id, weight)
//
// Author: Neuromorphic Accelerator Project
//-----------------------------------------------------------------------------

module synapse_csr #(
    parameter int NUM_NEURONS    = 139,
    parameter int WEIGHT_WIDTH   = 8,
    parameter int NUM_SYN        = 4810,
    parameter     CSR_DST_FILE    = "csr_dst.mem",
    parameter     CSR_WEIGHT_FILE = "csr_weight.mem",
    parameter     CSR_START_FILE  = "csr_start.mem",
    parameter     CSR_COUNT_FILE  = "csr_count.mem"
)(
    input  logic                        clk,

    // Pointer lookup — combinational
    input  logic [$clog2(NUM_NEURONS)-1:0] ptr_src_id,
    output logic [$clog2(NUM_SYN+1)-1:0]   ptr_base,
    output logic [$clog2(NUM_SYN+1)-1:0]   ptr_len,

    // Synapse read — 1-cycle latency
    input  logic [$clog2(NUM_SYN+1)-1:0]   syn_index,
    input  logic                           syn_rd_en,
    output logic [$clog2(NUM_NEURONS)-1:0]  syn_dst,
    output logic signed [WEIGHT_WIDTH-1:0]  syn_weight,
    output logic                            syn_valid
);

    localparam int ID_WIDTH       = $clog2(NUM_NEURONS);
    localparam int IDX_WIDTH      = $clog2(NUM_SYN + 1);
    localparam int FILE_ID_WIDTH  = 16;
    localparam int FILE_IDX_WIDTH = 24;

    // Connectivity storage
    logic [FILE_ID_WIDTH-1:0]       csr_dst    [0:NUM_SYN-1];
    logic signed [WEIGHT_WIDTH-1:0] csr_weight [0:NUM_SYN-1];
    logic [FILE_IDX_WIDTH-1:0]      src_start  [0:NUM_NEURONS-1];
    logic [FILE_IDX_WIDTH-1:0]      src_count  [0:NUM_NEURONS-1];

    initial begin
        $readmemh(CSR_DST_FILE,    csr_dst);
        $readmemh(CSR_WEIGHT_FILE, csr_weight);
        $readmemh(CSR_START_FILE,  src_start);
        $readmemh(CSR_COUNT_FILE,  src_count);
    end

    // Pointer lookup — where does source ptr_src_id's synapse list live?
    assign ptr_base = src_start[ptr_src_id][IDX_WIDTH-1:0];
    assign ptr_len  = src_count[ptr_src_id][IDX_WIDTH-1:0];

    // Synapse read — 1-cycle registered, like a synchronous memory
    always_ff @(posedge clk) begin
        syn_valid <= syn_rd_en;
        if (syn_rd_en) begin
            syn_dst    <= csr_dst[syn_index][ID_WIDTH-1:0];
            syn_weight <= csr_weight[syn_index];
        end
    end

endmodule
